### ISSUE TITLE
【guide】Make a Sentence

### ISSUE THREAD

**Issue by yujiangshui** [yujiangshui/A-Programmers-Guide-to-English-Practice#1]
## 今日单词：`guide`

请用上面单词进行造句，可以参照如下步骤：

**第一步：** 打开 [Cambridge Dictionary](https://dictionary.cambridge.org/) 查询该单词词义，并阅读全部内容，确保你十分明确这个单词的 **词性**、**词义** 以及常见例句和表达方法。

**第二步：** 结合你的日常和你想表达的意思**进行造句**，并进行如下检查：
* 尝试放入 Google 搜索，查看意思是否精准，或者有更合理的表达。
* 放入 [Grammarly](https://app.grammarly.com/) 进行基础语法检查，你并不想把语法有问题的句子发出来给大家看。

**第三步：** 检查无误之后，**作为回复发到对应 Issue 下面**。你也可以选择添加中文句意以方便别人学习你的表达方式。

**第四步：** 查看他人回答，并**对你觉得好的句子进行点赞**。

**第五步：** 如果你发现了明显的错误，或者某个句子有更好的表达，**请回复并为其指正**。当然你的回答也可能会被别人指正，**请不要害羞或者懊恼** ，这个世界上总有人英语比你学得好，有人指正才说明你有知识点掌握不好自己却不知道，更容易补齐自己的知识库。

更详细的说明请参照 [MAS](https://github.com/yujiangshui/A-Programmers-Guide-to-English-Practice/blob/master/README.md#mas---make-a-sentence)。

**Comment by yujiangshui** [comment]
Recently, I wrote a programmer's guide to English, and it may help you more or less.

近期我写了个给程序员看的英语指南，并且可能或多或少给你产生一些帮助。

**Comment by MacyMa18** [comment]
Whenever I travel to a new country, the Travel Guide always gives me some help.

每当我到新的国家旅行时，旅行指南总能给我一些帮助。

**Comment by ehlilier** [comment]
This is a great English learning guide, so do this issue.

**Comment by jianxiaoBai** [comment]
We all know that learn new thing need look guide also good guide and bad guide all can affect you learn speed, good guide can let you advance very fast, so when we are guide author, have to be earnest, because can affect very many people.
我们都知道学习新事物需要看指南，好的指导和不好的指南都会影响你学习速度，好的指南可以让你进步很快，所以当我们作为指南作者时，必须要认真, 因为会影响很多人。

**Comment by tenucc** [comment]
I failed to buy train tickets online, and I need a guide to 12306.cn.

**Comment by yujiangshui** [comment]
@jianxiaoBai 写的很认真，很赞。不过没有做过第二步，有一些比较明显的语法问题，可以修改下 ^_^

![image](https://user-images.githubusercontent.com/2942913/51104458-2aa5b100-1821-11e9-87b4-ad7122134b9f.png)

**Comment by yujiangshui** [comment]
@tenucc 如果我没猜错意思的话，我可能会写 `I could not buy train tickets online through myself, so I need a tool to guide me get a ticket from 12306.cn.` 感觉意思会详细一点点。

个人感觉这可能是个递进关系，没买到所以需要其他协助，so 可能比 and 更强一点点。然后 guide 这里我取了了动词 help 和指导的意思，因为 12306 官网并没有什么指南，我们更多可能用 tool（抢票插件）或者解决方案（开源框架和文档）solution 等来帮助或者指导我们抢票，那么对应前面我们为什么不能买到票呢？是因为 by myself 不行，所以要 by tools 了。

个人愚见，不保证完全正确。
