### ISSUE TITLE
【business】Make a Sentence

### ISSUE THREAD

**Issue by yujiangshui** [yujiangshui/A-Programmers-Guide-to-English-Practice#2]
## 今日单词：`business`

请用上面单词进行造句，可以参照如下步骤：

**第一步：** 打开 [Cambridge Dictionary](https://dictionary.cambridge.org/) 查询该单词词义，并阅读全部内容，确保你十分明确这个单词的 **词性**、**词义** 以及常见例句和表达方法。

**第二步：** 结合你的日常和你想表达的意思**进行造句**，并进行如下检查：
* 尝试放入 Google 搜索，查看意思是否精准，或者有更合理的表达。
* 放入 [Grammarly](https://app.grammarly.com/) 进行基础语法检查，你并不想把语法有问题的句子发出来给大家看。

**第三步：** 检查无误之后，**作为回复发到对应 Issue 下面**。你也可以选择添加中文句意以方便别人学习你的表达方式。

**第四步：** 查看他人回答，并**对你觉得好的句子进行点赞**。

**第五步：** 如果你发现了明显的错误，或者某个句子有更好的表达，**请回复并为其指正**。当然你的回答也可能会被别人指正，**请不要害羞或者懊恼** ，这个世界上总有人英语比你学得好，有人指正才说明你有知识点掌握不好自己却不知道，更容易补齐自己的知识库。

更详细的说明请参照 [MAS](https://github.com/yujiangshui/A-Programmers-Guide-to-English-Practice/blob/master/README.md#mas---make-a-sentence)。

**Comment by yujiangshui** [comment]
Learning new things is vital for you, that is not my business.

**Comment by yujiangshui** [comment]
@JackEggie 😂有其他建议吗？不过参与度不高，我明天就停掉了这个，就是演示下这个学习方法

**Comment by JackEggie** [comment]
@yujiangshui 一点拙见。

1. 死命宣传
2. 简化打卡模式，如在朋友圈打卡，github门槛相对高了，手机端不方便
3. 从github引流到微信群，把讨论放到微信群内，相信参与度会高很多，但可能会增加管理者工作量

**Comment by yujiangshui** [comment]
@JackEggie 感谢建议。其实有些我想过，但我回头想了下，我又不是老师，也不会从这个项目中获取什么收益。而且其实很多人只是 Mark 不会看或者看了也不会实践，我曾努力 push 或者推荐过别人一定要看，但后来想了下，学习都是自己的事情让别人推着是个什么鬼 😂

搞这个之前本来在群里征集了下意见，还有挺多赞同的，结果并没有什么人来参与的。但像你们这种行动派，其实并不需要这种活动也会行动起来学习英语。所以我找不到做这个事情的意义了，还得搭上我自己的时间。所以在这里演示下这个学习方法作罢。

**Comment by WUDINGDEJIE99** [comment]
这个开源的工具对于英语来说是一道坎，很多时候玩的不是顺手
